SOURCES += brueckenbauer.cc
SOURCES += fabrikbauer.cc
SOURCES += hausbauer.cc
SOURCES += tunnelbauer.cc
SOURCES += vehikelbauer.cc
SOURCES += warenbauer.cc
SOURCES += wegbauer.cc

include ../common.mk
