SOURCES += bridge_writer.cc
SOURCES += building_writer.cc
SOURCES += citycar_writer.cc
SOURCES += factory_writer.cc
SOURCES += good_writer.cc
SOURCES += image_writer.cc
SOURCES += imagelist2d_writer.cc
SOURCES += imagelist_writer.cc
SOURCES += obj_node.cc
SOURCES += obj_writer.cc
SOURCES += pedestrian_writer.cc
SOURCES += roadsign_writer.cc
SOURCES += root_writer.cc
SOURCES += sim_writer.cc
SOURCES += skin_writer.cc
SOURCES += text_writer.cc
SOURCES += tree_writer.cc
SOURCES += tunnel_writer.cc
SOURCES += vehicle_writer.cc
SOURCES += xref_writer.cc

include ../../common.mk
