SOURCES += bridge_reader.cc
SOURCES += building_reader.cc
SOURCES += citycar_reader.cc
SOURCES += crossing_reader.cc
SOURCES += factory_reader.cc
SOURCES += good_reader.cc
SOURCES += ground_reader.cc
SOURCES += image_reader.cc
SOURCES += obj_reader.cc
SOURCES += pedestrian_reader.cc
SOURCES += roadsign_reader.cc
SOURCES += root_reader.cc
SOURCES += sim_reader.cc
SOURCES += skin_reader.cc
SOURCES += tree_reader.cc
SOURCES += tunnel_reader.cc
SOURCES += vehicle_reader.cc
SOURCES += way_reader.cc
SOURCES += xref_reader.cc

include ../../common.mk
