// Generated by "get_pak.sh -generate_h"
#define PAKSET_COUNT 18
const char *pakinfo[PAKSET_COUNT*2] = {
	"http://downloads.sourceforge.net/project/simutrans/pak64/123-0/simupak64-123-0.zip", "pak64-123-0",
	"http://simutrans-germany.com/pak.german/pak64.german_0-123-0-0-2_full.zip", "pak64.german_0-123-0-0-2_full",
	"http://downloads.sourceforge.net/project/simutrans/pak64.japan/123-0/simupak64.japan-123-0.zip", "pak64.japan-123-0",
	"http://github.com/wa-st/pak-nippon/releases/download/v0.5.0/pak.nippon-v0.5.0.zip", "pak.nippon-v0.5.0",
	"https://github.com/Varkalandar/pak48.Excentrique/releases/download/v0.19_RC3/pak48.excentrique_v019rc3.zip", "pak48.excentrique_v019rc3",
	"http://downloads.sourceforge.net/project/simutrans/Pak128.CS/nightly%20builds/pak128.CS-r2078.zip", "pak128.CS-r2078",
	"http://downloads.sourceforge.net/project/simutrans/pak128.britain/pak128.Britain%20for%20120-3/pak128.Britain.1.18-120-3.zip", "pak128.Britain.1.18-120-3",
	"http://downloads.sourceforge.net/project/simutrans/PAK128.german/PAK128.german_2.1_for_ST_123.0/PAK128.german_2.1_for_ST_123.0.zip", "PAK128.german_2.1_for_ST_123.0",
	"http://downloads.sourceforge.net/project/simutrans/pak128/pak128%202.8.2%20for%20ST%20123up/simupak128-2.8.2-for123.zip", "pak128-2.8.2-for123",
	"http://github.com/Flemmbrav/Pak192.Comic/releases/download/2021-V0.6-RC2/pak192.comic.0.6.RC2.zip", "pak192.comic.0.6.RC2",
	"http://downloads.sourceforge.net/project/simutrans/pak96.comic/pak96.comic%20for%20111-3/pak96.comic-0.4.10-plus.zip", "pak96.comic-0.4.10-plus",
	"http://pak128.jpn.org/souko/pak128.japan.120.0.cab", "pak128.japan.120.0",
	"http://downloads.sourceforge.net/project/simutrans/pak32.comic/pak32.comic%20for%20102-0/pak32.comic_102-0.zip", "pak32.comic_102-0",
	"http://downloads.sourceforge.net/project/simutrans/pak64.contrast/pak64.Contrast_910.zip", "pak64.Contrast_910",
	"http://hd.simutrans.com/release/PakHD_v04B_100-0.zip", "PakHD_v04B_100-0",
	"http://downloads.sourceforge.net/project/simutrans/pakHAJO/pakHAJO_102-2-2/pakHAJO_0-102-2-2.zip", "pakHAJO_0-102-2-2",
	"http://downloads.sourceforge.net/project/simutrans/pak64.scifi/pak64.scifi_112.x_v0.2.zip", "pak64.scifi_112.x_v0.2",
	"http://simutrans.bilkinfo.de/pak64.ho-scale-latest.tar.gz", "pak64.ho-scale-latest",
};
