// Generated by "get_pak.sh -generate_h"
#define PAKSET_COUNT 17
const char *pakinfo[PAKSET_COUNT*2] = {
	"http://downloads.sourceforge.net/project/simutrans/pak64/122-0/simupak64-122-0.zip", "pak64-122-0",
	"http://simutrans-germany.com/pak.german/pak64.german_0-122-0-0-2_full.zip", "pak64.german_0-122-0-0-2_full",
	"https://downloads.sourceforge.net/project/simutrans/pak64.japan/120-0/simupak64.japan-120-0-1.zip", "pak64.japan-120-0-1",
	"https://github.com/wa-st/pak-nippon/releases/download/v0.4.0/pak.nippon-v0.4.0.zip", "pak.nippon-v0.4.0",
	"https://downloads.sourceforge.net/project/simutrans/pakHAJO/pakHAJO_102-2-2/pakHAJO_0-102-2-2.zip", "pakHAJO_0-102-2-2",
	"https://downloads.sourceforge.net/project/simutrans/pak96.comic/pak96.comic%20for%20111-3/pak96.comic-0.4.10-plus.zip", "pak96.comic-0.4.10-plus",
	"https://downloads.sourceforge.net/project/simutrans/pak128/pak128%20for%20ST%20120.4.1%20%282.8.1%2C%20priority%20signals%20%2B%20bugfix%29/pak128.zip", "pak128",
	"https://downloads.sourceforge.net/project/simutrans/pak128.britain/pak128.Britain%20for%20120-3/pak128.Britain.1.18-120-3.zip", "pak128.Britain.1.18-120-3",
	"http://downloads.sourceforge.net/project/simutrans/PAK128.german/PAK128.german_2.0_for_ST_122.0/PAK128.german_2.0_for_ST_122.0.zip", "PAK128.german_2.0_for_ST_122.0",
	"http://github.com/Flemmbrav/Pak192.Comic/releases/download/2021-V0.6-RC1/pak192.comic.0.6.RC1.zip", "pak192.comic.0.6.RC1",
	"https://downloads.sourceforge.net/project/simutrans/pak32.comic/pak32.comic%20for%20102-0/pak32.comic_102-0.zip", "pak32.comic_102-0",
	"https://downloads.sourceforge.net/project/simutrans/pak64.contrast/pak64.Contrast_910.zip", "pak64.Contrast_910",
	"https://hd.simutrans.com/release/PakHD_v04B_100-0.zip", "PakHD_v04B_100-0",
	"http://pak128.jpn.org/souko/pak128.japan.120.0.cab", "pak128.japan.120.0",
	"https://downloads.sourceforge.net/project/simutrans/pak64.scifi/pak64.scifi_112.x_v0.2.zip", "pak64.scifi_112.x_v0.2",
	"https://downloads.sourceforge.net/project/ironsimu/pak48.Excentrique/v018/pak48-excentrique_v018.zip", "pak48-excentrique_v018",
	"http://simutrans.bilkinfo.de/pak64.ho-scale-latest.tar.gz", "pak64.ho-scale-latest",
};
