/* prissi: first part is left, second part right side */

"","",
"","",
"","",
"","",
"","",
"","",
"","",
"Programming:","",
"","",
" Hajo","",
"","",
"","",
"Current Team (Standard):","",
" Markus Pristovsek","developer",
" Daniel Wachsmuth", "developer",
" Christoph Mallon","developer, SVN",
" TurfIt", "developer",
" Markohs", "3D branch",
"","",
"","",
"Additional Programming (Standard):","",
"","",
" Volker Meyer","big patches",
" Hendrik Siegeln","ex-developer",
" Niels Roest","GUI",
" Markus Weber","GUI changes",
" Owen Rudge","MIDI, patches",
" Tomas Kubes","patches",
" Rainer Bertram","patches",
" Andreas Röver","patches",
" Tilman Raatz","patches",
" Pasi Ruhanen","BeOS, SDL",
" Mat Hounsell","GUI",
" Kieron Green","skinned grounds",
" z9999","patches",
" Gerd Wachsmuth", "patches",
" Knightly", "ex-developer",
"","",
"","",
"Simutrans-Experimental:","",
"","",
" James E. Petts","design",
" Bernd Gabriel","coding",
" Knightly","coding",
" Nathanael Nerode","coding",
" Inkelyad", "coding",
" Isidoro","vehicle replacement",
" Hanczar","profiling, fixes",
" Ansgar","Linux builds, patches",
" Lefthand","patches",
" Nathan Samson","patches",
" Yobbobandana","patches",
" Carl Baker","patches",
" Richard Smith","patches",
" HeinBloed","patches",
" Omikron","patches",
" Kieron Green","patches",
" Darkbill","patches",
" Markus Pristovsek","coding advice",
" Daniel Wachsmuth","coding advice",
" Giuseppe", "Italian translation",
" deMangler","multiplayer testing and hosting",
" Sdog","beta testing",
" Colin","beta testing",
" Tick Tock","beta testing",
" Z9999","beta testing",
" Colonyan","beta testing",
" Jeffatsqi","beta testing",
" Whoami","beta testing",
" Sojo","beta testing",
" Comrade","beta testing",
" dantedarkstar","beta testing",
" Tuxedohamm","beta testing",
" Michael Woodburn","beta testing",
" Susanna Björverud","beta testing",
" Cyrus Hall","beta testing",
" AvG","beta testing",
" Pavulon","beta testing",
" Werl","beta testing",
" Berksen","beta testing",
" Kleinad","beta testing",
" Drs01","beta testing",
" Mjhn","beta testing",
" Megasycophant","beta testing",
" Rsdworker","beta testing",
" Miar192gep","beta testing",
" Ivan Sanchez","beta testing",
" Waerth","beta testing",
" David H.","beta testing",
" Junna","beta testing",
" Blaine","beta testing",
" Turfit","beta testing",
" Steffen","beta testing",
" Sdog","beta testing",
" AEO","beta testing",
" Dutchman on Rails","beta testing",
" Brambo","beta testing",
" mopoona","beta testing",
" Quarks","beta testing",
" fbfree","beta testing",
" Djohaal","beta testing",
" Giuseppe","beta testing",
" Dustin","beta testing",
" chs","beta testing",
" Leva","beta testing",
" fbfree","beta testing",
" Erik","beta testing",
" An_dz","beta testing",
" Dannyman","beta testing",
" Merry","beta testing",
" Jk271","beta testing",
" Arch Chancellor","beta testing",
" AP","beta testing",
" W. Lindley","beta testing",
" mgp104","beta testing",
" Lakehaze","beta testing",
" asaphxiix","beta testing",
" almaf","beta testing",
" treiskin","beta testing",
" Sholong","beta testing",
" Mau","beta testing",
" Chicken","beta testing",
"","",
"","",
"Game Design Assistance:","",
"","",
" Peter J. Dobrovka","",
" Tomas Kubes","",
" Vladimir Slavik", "pak128",
"","",
" Frank Penz","pak.german",
"","",
" Yoshihiro Shishido","pak.japan128",
"","",
" Kieron Green","",
" James Hood","Pak128.Britain",
" Special thanks to:", "",
" The National Railway Museum, York", "",
"","",
" Michael Hohl","",
" PappeTeeMaster","",
" Schnils","Pak192.Comic",
"","",
" Sven Osada","pak96.comic",
"","",
"Graphics:","",
"","",
" Flor Wauters","",
" Georg 'MHz' Moers","",
" Hansjörg Malthaner","",
" James Starr","",
" Manfred Tomaschitz","",
" Oskari 'TPI' Saarekas","",
" Patrick Nesbitt","",
" Peter J. Dobrovka","",
" Rick 'Trikky' McGreal","",
" Sergiu Croitor","",
" Seth C. Triggs","",
" Tomas Kubes","",
" Guillermo 'raven' Mateo","",
" Alexander Brose","",
"","",
"and many more","",
"","",
"","",
"Translation:","",
"","",
" Alberto Beccaria","Italian",
" George Dragon","Hungarian",
" Hansjörg Malthaner","German",
" Bernd Gabriel","German (Experimental)",
" Marcal Guardiola","Spanish",
" Niels Roest","Dutch",
" Pasi Ruhanen","Finnish",
" Rémi Denis-Courmont","French",
" Ferencz Szekely","Hungary & Romanian",
" Alex Revo","Russian",
" Roman Schwörer","French & German",
" Yannis Kaskamanid", "Greek",
" Igor Eliezer", "Portuguese",
" Joan-Josep Bargues", "Catalan",
" Susanna Björverud", "Swedish",
" Xavier Paz", "Spanish",
" Wim Vreeswijk", "Dutch",
" Paul Color", "Swedish",
" Ignas Brasiskis", "Lithuanian",
"","",
"and many more","",
"","",
"","",
"Additional Thanks go to:","",
"","",
" Bernhard Mecl","",
"","the very first Simutrans beta tester",
" Bram Schoenmakers","",
"","the most critical tester",
" Gerhard Hafner","",
"","for providing tons of railway information",
" Marcus Haupt","",
"","for lots of help with tricky problems",
" Vern Moorhouse", "",
"","for some valuable technical hints",
" Isaac Eiland-Hall","",
"","hosting simutrans.com",
" Dirk Burkholz","",
"","hosting german Forum",
" Frank Penz", "",
"", "Simutranslator, Wiki, and more",
" Christoph Mallon", "",
"", "hosting the SVN",
" werniman", "",
"", "nightly builds",
"","",
"", "",
" And many thanks to all testers and","",
" players, and all who supported the","",
" project!","",
"","",
"","",
"","",
"","",
"","",
"","",
"","",
0
