/* prissi: first part is left, second part right side */

"","",
"","",
"","",
"","",
"","",
"","",
"","",
"Programming:","",
"","",
" Hansjörg Malthaner","",
"","",
"","",
"Additional Programming:","",
"","",
" Volker Meyer","big patches",
" Hendrik Siegeln","ex developer",
" Niels Roest","GUI",
" Markus Weber","GUI changes",
" Markus Pristovsek","current head",
" Owen Rudge","MIDI, patches",
" Tomas Kubes","misc. patches",
" Rainer Bertram","misc. patches",
" Andreas Röver","misc. patches",
" Tilman Raatz","misc. patches",
" Pasi Ruhanen","BeOS, SDL",
" Mat Hounsell","GUI",
" Christoph Mallon","Makefile, patches",
" Kieron Green","skinned grounds",
" z9999","misc. patches",
" Daniel W.", "developer"
" Gerd Wachsmuth", "patches"
"","",
"","",
"Simutrans-Experimental:","",
"","",
"James E. Petts","design",
"Isidoro","vehicle replacement",
"Gerw","signal automation",
"Knightly","beta testing, optimisation",
"Ansgar","Linux builds, patches",
"Colin","beta testing",
"Tick Tock","beta testing",
"Z9999","beta testing",
"Colonyan","beta testing",
"jeffatsqi","beta testing",
"Whoami","beta testing",
"Sojo","beta testing",
"Tttron","beta testing",
"comrade","beta testing",
"","",
"","",
"Game Design Assistance:","",
"","",
" Peter J. Dobrovka","",
" Tomas Kubes","pak128",
" Frank Penz","pak.german",
" Yoshihiro Shishido","pak.japan128",
" Kieron Green","",
" James Hood","Pak128.Britain",
" Michael Hohl","",
" PappeTeeMaster","",
" Schnils","Pak192.Comic",
"","",
"","",
"Graphics:","",
"","",
" Flor Wauters","",
" Georg 'MHz' Moers","",
" Hansjörg Malthaner","",
" James Starr","",
" Manfred Tomaschitz","",
" Oskari 'TPI' Saarekas","",
" Patrick Nesbitt","",
" Peter J. Dobrovka","",
" Rick 'Trikky' McGreal","",
" Sergiu Croitor","",
" Seth C. Triggs","",
" Tomas Kubes","",
" Guillermo 'raven' Mateo","",
" Alexander Brose","",
"","",
"and many more","",
"","",
"","",
"Translation:","",
"","",
" Alberto Beccaria","Italian",
" George Dragon","Hungarian",
" Hansjörg Malthaner","German",
" Marcal Guardiola","Spanish",
" Niels Roest","Dutch",
" Pasi Ruhanen","Finnish",
" Rémi Denis-Courmont","French",
" Ferencz Szekely","Hungary & Romanian",
" Alex Revo","Russian",
" Roman Schwörer","French & German",
" Yannis Kaskamanid", "Greek",
" Igor Elizer", "Portugese",
" Joan-Josep Bargues", "Catalan",
" Susanna Björverud", "Swedish",
" Xavier Paz", "Spanish",
" Vladimir Slavik", "Czech",
" Wim Vreeswijk", "Dutch",
" Paul Color", "Swedish",
" Ignas Brasiskis", "Lithuanian",
"","",
"and many more","",
"","",
"","",
"Additional Thanks go to:","",
"","",
" Bernhard Mecl","",
"","the very first Simutrans beta tester",
" Bram Schoenmakers","",
"","the most critical tester",
" Gerhard Hafner","",
"","for providing tons of railway information",
" Marcus Haupt","",
"","for lots of help with tricky problems",
" Vern Moorhouse", "",
"","for some valuable technical hints",
" Isaac Eiland-Hall","",
"","hosting simutrans.com",
" Dirk Burkholz","",
"","hosting wiki and german Forum",
" Frank Penz", "",
"", "Simutranslator and more"
"","",
"", "",
" And many thanks to all testers and","",
" players, and all who supported the","",
" project!","",
"","",
"","",
"","",
"","",
"","",
"","",
"","",
0
