/*
 * scrolltext.h
 *
 * Copyright (c) 1997 - 2001 Hansjörg Malthaner
 *
 * This file is part of the Simutrans project and may not be used
 * in other projects without written permission of the author.
 */

/* prissi: first part is left, second part right side */

"","",
"","",
"","",
"","",
"","",
"","",
"","",
"Programming:","",
"","",
" Hansjörg Malthaner","",
"","",
"","",
"Additional Programming:","",
"","",
" Volker Meyer","big patches",
" Hendrik Siegeln","patches",
" Niels Roest","GUI",
" Markus Weber","GUI changes",
" Markus Pristovsek","patches",
" Owen Rudge","MIDI, patches",
" Tomas Kubes","misc. patches",
" Hellmade","misc. patches",
" Andreas Röver","misc. patches",
" Tilman Raatz","misc. patches",
" Pasi Ruhanen","BeOS, SDL",
" Mat Hounsell","GUI",
"","",
"","",
"Game Design Assistance:","",
"","",
" Peter J. Dobrovka","",
"","",
"","",
"Graphics:","",
"","",
" Flor Wauters","",
" Georg 'MHz' Moers","",
" Hansjörg Malthaner","",
" James Starr","",
" Manfred Tomaschitz","",
" Oskari 'TPI' Saarekas","",
" Patrick Nesbitt","",
" Peter J. Dobrovka","",
" Rick 'Trikky' McGreal","",
" Sergiu Croitor","",
" Seth C. Triggs","",
" Tomas Kubes","",
"","",
"","",
"Translation:","",
"","",
" Alberto Beccaria","Italian",
" George Dragon","Hungarian",
" Hansjörg Malthaner","German",
" Marcal Guardiola","Spanish",
" Niels Roest","Dutch",
" Pasi Ruhanen","Finnish",
" Rémi Denis-Courmont","French",
" Ferencz Szekely",""
"","Hungary and Romanian"
" 'StalkeRXP'","Russian"
"","",
"","",
"Manual and Documentation:","",
"","",
" Hansjörg Malthaner","",
" Henrik Wolff","",
" Dirk Burkholz","",
"","",
"","",
"Additional Thanks go to:","",
"","",
" Bernhard Mecl","",
"","the very first Simutrans beta tester",
"","",
" Bram Schoenmakers","",
"","the most critical tester",
"","",
" Gerhard Hafner","",
"","for providing tons of railway",
"","information",
"","",
" Marcus Haupt","",
"","for lots of help with tricky problems",
"","",
" Vern Moorhouse", "",
"","for some valuable technical hints",
"","",
"", "",
" And many thanks to all testers and","",
" players, and all who supported the","",
" project!","",
"","",
"","",
"","",
"","",
"","",
"","",
"",""
