SOURCES += gui_chart.cc
SOURCES += gui_combobox.cc
SOURCES += gui_divider.cc
SOURCES += gui_flowtext.cc
SOURCES += gui_resizer.cc
SOURCES += gui_speedbar.cc
SOURCES += gui_textarea.cc
SOURCES += gui_textinput.cc

include ../../common.mk
