SOURCES += boden.cc
SOURCES += brueckenboden.cc
SOURCES += fundament.cc
SOURCES += grund.cc
SOURCES += monorailboden.cc
SOURCES += tunnelboden.cc
SOURCES += wasser.cc

SUBDIRS = wege

include ../common.mk
