SOURCES += baum.cc
SOURCES += bruecke.cc
SOURCES += dummy.cc
SOURCES += gebaeude.cc
SOURCES += lagerhaus.cc
SOURCES += leitung2.cc
SOURCES += oberleitung.cc
SOURCES += pillar.cc
SOURCES += raucher.cc
SOURCES += roadsign.cc
SOURCES += signal.cc
SOURCES += tunnel.cc
SOURCES += wolke.cc
SOURCES += zeiger.cc

include ../common.mk
