SOURCES += dingliste.cc
SOURCES += einstellungen.cc
SOURCES += fahrplan.cc
SOURCES += freelist.cc
SOURCES += koord.cc
SOURCES += koord3d.cc
SOURCES += koord3d.cc
SOURCES += linie.cc
SOURCES += loadsave.cc
SOURCES += marker.cc
SOURCES += powernet.cc
SOURCES += ribi.cc
SOURCES += route.cc
SOURCES += tabfile.cc
SOURCES += translator.cc
SOURCES += umgebung.cc
SOURCES += warenziel.cc

include ../common.mk
