// Generated by "get_pak.sh -generate_h". DO NOT EDIT.
#define PAKSET_COUNT 20
#define OBSOLETE_FROM (11)
paksetinfo_t pakinfo[PAKSET_COUNT] = {
	{ "http://downloads.sourceforge.net/project/simutrans/pak64/124-1/simupak64-124-1.zip", "pak", "pak64 124.1 r2156", 15869 },
	{ "http://downloads.sourceforge.net/project/simutrans/pak128/pak128%20for%20ST%20%20124.1up%20%282.9.1%29/simupak128-2.9.1.zip", "pak128", "pak128 2.9.1 for 124.1.0 git r579 hash c3519a4", 414630 },
	{ "http://downloads.sourceforge.net/project/simutrans/pak192.comic/pak192.comic%20V0.7.1/pak192-comic.zip", "pak192.comic", "Pak192.Comic V0.7.1 Rev 1246", 892852 },
	{ "http://simutrans-germany.com/pak.german/pak64.german_0-124-0-0-3_full.zip", "pak64.german", "pak64.german 0.124.0.0.3", 26348 },
	{ "http://downloads.sourceforge.net/project/simutrans/pak64.japan/123-0/simupak64.japan-123-0.zip", "pak.japan", "pak64.japan 123 r2101", 10175 },
	{ "https://github.com/wa-st/pak-nippon/releases/download/v0.6.2/pak.nippon-v0.6.2.zip", "pak.nippon", "pak.nippon v0.6.2", 50198 },
	{ "http://downloads.sourceforge.net/project/simutrans/Pak128.CS/nightly%20builds/pak128.CS-r2096.zip", "pak128.CS", "Pak128.CS 0.3.0 r2096", 78628 },
	{ "http://downloads.sourceforge.net/project/simutrans/pak128.britain/pak128.Britain%20for%20120-3/pak128.Britain.1.18-120-3.zip", "pak128.Britain", "pak128.Britain 1.18 120.3 r1991", 241715 },
	{ "http://downloads.sourceforge.net/project/simutrans/PAK128.german/PAK128.german_2.2_for_ST_124.0/PAK128.german_2.2_for_ST_124.0.zip", "PAK128.german", "Pak128.german VS 2.2 (Rev. 500)", 562328 },
	{ "https://github.com/Varkalandar/pak144.Excentrique/releases/download/r0.08/pak144.Excentrique_v008.zip", "pak144.Excentrique", "pak144.Excentrique v0.08", 7621 },
	{ "http://downloads.sourceforge.net/project/simutrans/pakTTD/simupakTTD-124-0.zip", "pakTTD", "pak64 120.4.1 r2146", 1995 },
	{ "http://downloads.sourceforge.net/project/simutrans/pak96.comic/pak96.comic%20for%20111-3/pak96.comic-0.4.10-plus.zip", "pak96.comic", "pak96.comic V4.1 plus", 32526 },
	{ "http://pak128.jpn.org/souko/pak128.japan.120.0.cab", "pak128.japan", "Pak128.Japan 120.0", 27780 },
	{ "http://downloads.sourceforge.net/project/simutrans/pak32.comic/pak32.comic%20for%20102-0/pak32.comic_102-0.zip", "pak32", "", 3420 },
	{ "https://github.com/Varkalandar/pak48.Excentrique/releases/download/v0.19_RC3/pak48.excentrique_v019rc3.zip", "pak48.Excentrique", "pak48.Excentrique v0.19", 2016 },
	{ "http://downloads.sourceforge.net/project/simutrans/pak64.contrast/pak64.Contrast_910.zip", "pakcontrast", "", 1440 },
	{ "http://hd.simutrans.com/release/PakHD_v04B_100-0.zip", "pakHD", "Martin", 12515 },
	{ "http://downloads.sourceforge.net/project/simutrans/pakHAJO/pakHAJO_102-2-2/pakHAJO_0-102-2-2.zip", "pakHAJO", "", 7460 },
	{ "http://downloads.sourceforge.net/project/simutrans/pak64.scifi/pak64.scifi_112.x_v0.2.zip", "pak64.scifi", "pak64.SciFi V0.2", 3293 },
	{ "http://simutrans.bilkinfo.de/pak64.ho-scale-latest.tar.gz", "pak64.ho-scale", "", 9022 },
};
